Сделал реализацию drag&drop + проверку + nextWord
eshavrov/deu-server pull request #6
Opened 2021-11-06 07:58 UTC by rasul-surname

2021-11-06 10:13 UTC, eshavrov requested changes

2021-11-06 10:13 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +    }
```js
const randomArr = Array.from(arr, (_, index) => index);
```
Если делаешь простую вещь, то и кодом выражай проще, более декларативно

у Array  существует статический метод from. он позволяет создать новый экземпляр массива из объекта напоминающего массив (в нашем случае массива) второй аргумент напоминает колбек из метода map.

2021-11-06 10:13 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +    }
или хотя бы так
```js
const randomArr = arr.map((_, index) => index);
```
это тоже самое, но просто через. map.

Зачем повышать когнитивную нагрузку на те места где это не нужно. 
если что то новое написал подкрепляй знания читай точечно доку

2021-11-06 10:13 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  function nextWord() {
Писал выше, не нужна эта логика внутри данного компонента. он решает задачу одного теста а не группы

2021-11-06 11:04 UTC, eshavrov requested changes

2021-11-06 11:04 UTC, eshavrov commented on src/pages/feature/anagramma/Anagramma.module.scss
>  }
у тебя отсутствует управление отступами между буквами. Данными сущностями лучше что бы управлял контейнер, а не сам элемент.

у `flex` и `grid` есть свойство gap для этого
если необходимо убери отступы у компонента буквы) в самом компоненте конечно!

2021-11-06 11:22 UTC, eshavrov requested changes

2021-11-06 11:22 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +import s from './Anagramma.module.scss';
Сортируй импорты 
сначала идут те что описаны в наших зависимостях (package.json, к примеру, `react`, `cn`, `lodash` и тп)

потом делаешь пробел

далее идут те что ты получаешь через алиасы (к примеру `@componants/..`, `@constants`) их тоже между собой можешь отсортировать

потом делаешь пробел

и уже локальные импорты которые нужны только этому конкретному модулю (к примеру, `from './....'`;

2021-11-06 12:31 UTC, rasul-surname commented on src/pages/feature/anagramma/Anagramma.module.scss
> +
Не заметил(

2021-11-06 12:57 UTC, rasul-surname commented on src/pages/feature/anagramma/index.tsx
> +  function dragEndHandler(e) {
Это на будущее, цвет менять предполагалась 
Убрал

2021-11-06 13:02 UTC, rasul-surname commented on src/pages/feature/anagramma/index.tsx
> +    }
Agree with you

2021-11-07 11:31 UTC, eshavrov requested changes

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +    setItem(item + 1);
Компонент не должен знать о других словах.

Но и в записи есть проблема. React асинхронный, если изменения зависят от предыдущего состояния, то нужно это изменение делать через каллбек.

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +        <Button onClick={nextWord}>Пропустить</Button>
Убери всю логику связанную с nextWord. Компонент должен знать только об одном слове!

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +    const random = Math.floor(Math.random() * (result.length - 1 - 0 + 1) + 0);
Я же тебе писал про -1-0+1 +0!!!!!!
Убери лишнее!

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  const [data, setData] = React.useState([
Должно быть одно слово из пропсов

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  const [data, setData] = React.useState([
data лишняя сущность

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  const [item, setItem] = React.useState(0);
компонент не должен знать о том какое это слово, он работает со словом которое пришло из пропсов.

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  const [newCard, setNewCard] = React.useState(null);
возможно стоит поменять нейминг 
Пишешь о букве, а называешь карточкой.

А то слишком много терминов, голова кругом когда читаешь этот небольшой код

Думаю стоит отталкиваться от слов `char(character), letter, symbol,...` (символ, ведь могут быть и дефисы и пробелы)

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  const [newCard, setNewCard] = React.useState(null);
Если используешь VS CODE, есть замечательная функция F2 [Rename symbol](https://www.youtube.com/watch?v=S1Jzrmw0ww8)

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  const [newCard, setNewCard] = React.useState(null);
Досмотри до конца (спойлер, работает и с JSX)

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
>    function dragStartHandler(e, elem) {
Лично я не люблю такой нейминг:
`dragStartHandler` я бы назвал `_onDragStart`

во всем проекте будет именно такой
исправь пожалуйста

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
>    function dragOverHandler(e) {
я бы не стал сокращать `event` -> `e` (Согласен, что так делают многие)

Сокращение `e` приемлемо для объекта ошибки (`error`). давай `event` будем писать полностью

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/Anagramma.module.scss
>    margin-bottom: 50px;
Буквы наверное склеились, добавь расстояние между ними

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/Anagramma.module.scss
>    margin-bottom: 50px;
используй для этого css-переменную

2021-11-07 11:31 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  function passWord() {
не нужно делать управление состоянием внутри этой функции. Сделай из нее чистую функцию и вынеси её из компонента

2021-11-07 11:37 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +    const obj = arr.reduce(function(sum, elem, index, array) {
В итоге переписал но последний аргумент `arr` опять оставил? если ты его не используешь, то удаляй

2021-11-07 11:38 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +  const sortCards = (a, b) => {
Она все еще внутри, вынеси за пределы компонента

2021-11-07 11:40 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +        Math.random() * (result.length - 1 - 0 + 1) + 0,
??? все еще тут?

2021-11-08 05:45 UTC, rasul-surname commented on src/pages/feature/anagramma/index.tsx
> +  const [newCard, setNewCard] = React.useState(null);
WebShtorm использую

2021-11-08 05:54 UTC, rasul-surname commented on src/pages/feature/anagramma/index.tsx
> +        <Button onClick={nextWord}>Пропустить</Button>
Переписал на:

<Button onClick={() => setItem(item + 1)}>Пропустить</Button>

2021-11-08 05:55 UTC, rasul-surname commented on src/pages/feature/anagramma/index.tsx
> +    setItem(item + 1);
Переписал на:

<Button onClick={() => setItem(item + 1)}>Пропустить</Button>

2021-11-08 07:02 UTC, eshavrov requested changes

2021-11-08 07:02 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +      <hr className={s.line}/>
Опять забываешь про линтинг

2021-11-08 07:02 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +              onDragOver={(event) => onDragOver(event)}
зачем здесь лишняя функция? вызывай сразу, ты же просто передаешь тот же аргумент

2021-11-08 07:02 UTC, eshavrov commented on src/pages/feature/anagramma/index.tsx
> +        <Button onClick={() => setItem(item + 1)}>Пропустить</Button>
`setItem` асинхронная функция, ты ее неправильно используешь

2021-11-09 09:59 UTC, eshavrov requested changes

2021-11-09 09:59 UTC, eshavrov commented on src/client/components/feature/anagramma/index.tsx
> +  return result === word ? alert('true') : alert('false');
Если функция называется `checkBlahBlahBla() => boolean;`
то ожидается что она вернет `true`, либо `false`.

2021-11-09 09:59 UTC, eshavrov commented on src/client/components/feature/anagramma/index.tsx
> +  return result === word ? alert('true') : alert('false');
У тебя очень странная конструкция не имеющая смысла! `alert` ничего не возвращает (`undefined`).

2021-11-09 09:59 UTC, eshavrov commented on src/client/components/feature/voices/index.tsx
> +  { value: 'it', label: 'Италианском' },
Опечатка с слове, исправь

2021-11-09 09:59 UTC, eshavrov commented on src/pages/feature/anagramma.tsx
> +  const state = [
удали не используемые переменные.
сделай `npm run lint:ts`. И исправь все проблемы

2021-11-09 09:59 UTC, eshavrov commented on src/client/components/feature/anagramma/index.tsx
> +  const [currentWord, setCurrentWord] = React.useState([]);
переименуй `currentWord` так что бы было понятно что это массив. сейчас по названию кажется что это скорее строка . к примеру `charList` или `chars`

2021-11-09 09:59 UTC, eshavrov commented on src/client/components/feature/anagramma/index.tsx
> +  const [currentWord, setCurrentWord] = React.useState([]);
и не забудь название функции для изменения состояния переименовать, соотвественно

2021-11-09 09:59 UTC, eshavrov commented on src/client/components/feature/anagramma/index.tsx
> +//Преобразует строку в массив случайных элементов
Лучше добавлять в комментариях ведущий пробел
```js
// Преобразует строку в массив случайных элементов
```
так просто принято

2021-11-09 09:59 UTC, eshavrov commented on src/client/components/feature/anagramma/index.tsx
> +              onDragOver={(event) => onDragOver(event)}
Зачем здесь функция в функции?

2021-11-09 10:02 UTC, eshavrov requested changes

2021-11-09 10:02 UTC, eshavrov commented on src/client/components/feature/anagramma/index.tsx
> +function checkWord(symbols, word) {
Возможно эта функция не работает как ожидается) точно работает?

2021-11-09 12:15 UTC, rasul-surname commented on src/client/components/feature/anagramma/index.tsx
> +function checkWord(symbols, word) {
Да, я проверяю перед тем как запушить что-то

Она возвращает alert true если правильно и false если нет

2021-11-09 12:18 UTC, rasul-surname commented on src/client/components/feature/anagramma/index.tsx
> +  return result === word ? alert('true') : alert('false');
Не знаю про что ты

Всё работает как швейцарские часы

2021-11-09 12:19 UTC, rasul-surname commented on src/pages/feature/anagramma/index.tsx
> +              onDragOver={(event) => onDragOver(event)}
Переименовал

2021-11-09 19:22 UTC, merged